name: automate_dv_cli_sample_project
profile: cli_project
version: '0.1.0'
require-dbt-version: ['>=1.0.0', '<2.0.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
  - dbt_packages
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '1992-01-08'
  tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  automate_dv_cli_sample_project:
    raw_stage:
      tags:
        - 'raw'
      materialized: view
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
