version: 2
sources:
- name: SDQV
  database: MARDIROSG
  schema: DBT_DEMO
  tables:
  - name: HUB_DQ_LOADS
  - name: HUB_DQ_TEST_RESULTS
  - name: HUB_DQ_TEST_RUNS
  - name: HUB_REF_DQ_TESTS
  - name: HUB_REF_OBJECTS
  - name: LNK_DQTESTRESULTS_DQTESTRUNS
  - name: LNK_DQTESTRESULTS_REFDQTESTS
  - name: LNK_DQTESTRESULTS_REFOBJECTS
  - name: LNK_DQTESTRUNS_DQLOADS
  - name: SAT_SAT_DQL_DQ_LOADS
  - name: SAT_SAT_DQL_DQ_TEST_RESULTS
  - name: SAT_SAT_DQL_DQ_TEST_RUNS
  - name: SAT_SAT_DQL_REF_DQ_TESTS
  - name: SAT_SAT_DQL_REF_OBJECTS
  - name: bridge_br_dq_testresult_detail
  - name: pit_pit_ref_data
