version: 2
sources:
- name: BK
  database: GILLESL
  schema: BANKING_DEMO
  tables:
  - name: ACCOUNT
  - name: ACCOUNT_HOLDER
  - name: BANK_TRANSACTION
  - name: BRANCH
  - name: CURRENCY
  - name: PARTY
  - name: PARTY_ADDRESS
  - name: PRODUCT
