version: 2
sources:
- name: BK
  database: AUTOMATE_DV_DBT_DEMO
  schema: BANKING_DEMO
  tables:
  - name: DQ_LOADS
  - name: DQ_TEST_RESULTS
  - name: DQ_TEST_RUNS
  - name: REF_DQ_TESTS
  - name: REF_OBJECTS
